### PR TITLE
Document addressBooks.provider

### PR DESCRIPTION
**Pull request by benbucksch**
Explain when to use cached address books and the existing APIs, and when
to use the new API.

Explain how search-only address books work, when the event fires, and what
the effects are. Show sample usage.

### CODE REVIEW

**Comment by benbucksch** [comment]
TODO: Move and format the documentation for `extraParameters`. I'd added the text, but I don't know where it does in the doc.

**Comment by jobisoft** [comment]
Thanks, I will take care of extraParameter.

Could you add a one line description for 
https://github.com/thundernest/webext-docs/blame/master/index.rst#L94

**Comment by jobisoft** [comment]
The generator script was not aware of the `extraParameter` for events, so I had to rework that first, before I am able to merge this properly. This is how the new layout (without the PR) looks like:
https://webextension-api.thunderbird.net/en/91/addressBooks.provider.html#onsearchrequest

I will need a bit more time to get the new layout working.

But while looking at the new API, I have a question: Why do we need the `id` in the extraParameter? If I register a listener, this automatically creates a new address book and any requests to that address book should only be send to the listener associated with that address book.

If I register a second listener, that should create a new address book and its listener should never get called by the first address book. What is the API doing currently? What is a potential uses case to have cross address book callbacks?

**Comment by jobisoft** [comment]
Or does the id parameter allow to register a listener for an already existing provider address book, without creating a new one?

**Comment by benbucksch** [comment]
> The generator script was not aware of the extraParameter for events ... This is how the new layout (without the PR) looks like:
> https://webextension-api.thunderbird.net/en/91/addressBooks.provider.html#onsearchrequest

Thanks, this is much better! Even for addListeners without parameters, the header "Parameters passed to the listener function" will make it much clearer. This is good even for other APIs.

I can see that by default, it takes the documentation from the JSON source file as text. This is great. (If it's possible to override or amend the text, in the rst, like we do here.)

> If I register a second listener, that should create a new address book and its listener should never get called by the first address book.

That is correct, and that's the current behavior. (If you see something else, that's a bug.)

The purpose is so that one extension can add several address books, e.g. multiple address books for a single server account, or multiple server accounts.

**Comment by benbucksch** [comment]
> Why do we need the id ...?

That's explained in the documentation that I wrote :-)

"`id`: (Optional) The UID of the address book. If you add several listeners, that allows you to identify which address book the search event came from. If not passed, an UID will be generated for you."

The technical reason for doing it this way is that we cannot easily return the ID from the addListener function, so it was easier to let the caller pass it in, optionally.

> does the id parameter allow to register a listener for an already existing provider address book, without creating a new one?

No, the code enforces that the ID is new and unique, if it's passed in, otherwise it creates one.

**Comment by jobisoft** [comment]
>  (If it's possible to override or amend the text, in the rst, like we do here.)

Yes, that is possible via the overlay directory. After the documentation has evolved and has reached a stable wording, I usually push the changes back to the source file, to have as little overrides/overlays as possible.

**Comment by benbucksch** [comment]
> I usually push the changes back to the source file

Great!

**Comment by jobisoft** [comment]
@benbucksch : We are moving these example snippets into the tree, to reduce the number of places which need to be modified in order to generate the docs. The ultimate goal is to establish a fully automatic code-to-documentation process.

The snippets in the tree will be released as Public Domain:
https://phabricator.services.mozilla.com/D252284

This repository does not have a license, so your contribution is fully owned by you. Do you agree to re-release these snippets as public domain? Otherwise, we have to remove the snippet from our documentation. Thanks for your support!

**Pull request merged**
